# Generated by Django 3.2.5 on 2021-07-22 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_auto_20210722_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='employe',
            field=models.ManyToManyField(related_name='employe_or_member_many_to_many', to=settings.AUTH_USER_MODEL),
        ),
    ]
