# Generated by Django 3.2.5 on 2021-07-22 16:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_accounts_employe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="phone_fax",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
