# Generated by Django 3.2.5 on 2021-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_category_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="icons",
            field=models.ImageField(null=True, upload_to="product/"),
        ),
    ]
