# Generated by Django 3.2.5 on 2021-07-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20210728_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Hex',
        ),
        migrations.RenameField(
            model_name='hex',
            old_name='hex',
            new_name='color',
        ),
    ]
