# Generated by Django 3.2.5 on 2021-07-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210728_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='galery',
        ),
    ]
