# Generated by Django 3.2.5 on 2021-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_auto_20210729_1045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product",
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=225, unique=True)),
                ("name", models.CharField(max_length=225)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField()),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product_many_to_many", to="database.Product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="sub",
            field=models.ManyToManyField(
                related_name="sub_category_many_to_many", to="database.SubCategory"
            ),
        ),
    ]
